### ISSUE TITLE
mutator:0 failed: hash tx failed: empty network passphrase

### ISSUE THREAD

**Issue by hocokbkapmahe** [trusch/stellarctl#2]
Hello,

Everytime when I want to trust/send lumens I got
`mutator:0 failed: hash tx failed: empty network passphrase`

How I can set network passphrase from the command-line ?
Thanks

**Comment by hocokbkapmahe** [comment]
Any ideas ?

**Comment by trusch** [comment]
It could be that the semantics of the mutators changed, i.e. it doesn't
assume the public network as default. I'll have a look and will update this
issue

hocokbkapmahe <notifications@github.com> schrieb am Do., 24. Mai 2018,
15:33:

**Comment by hocokbkapmahe** [comment]
It would be great !
Thanks

**Comment by jessicard** [comment]
I just ran into this too 🤔

**Comment by trusch** [comment]
fixed!

**Comment by jessicard** [comment]
@trusch Thanks for fixing this! mind cutting a new release?
